.\" Manpage for YACReaderLibrary.
.\" Contact yoann.gauthier9@gmail.com to correct errors or typos.
.TH man 8 "5 July 2014" "1.0" "YACReaderLibrary man page"
.SH NAME
YACReaderLibrary \- launch YACReaderLibrary application.
.SH SYNOPSIS
.B
YACReaderLibrary
.SH DESCRIPTION
YACReaderLibrary an application for browsing and managing your comic collections with various smooth transition effects
.SH OPTIONS
No command line parameters.
.SH FEATURES
- Create, manage and browse your comics collections using beautiful, customizable and smooth "comic flow" transitions.
.TP
- Comic Vine support.
.TP
- Easily organization of your comics in libraries.
.TP
- Find your comics quickly using the built-in search engine.
.TP
- Open your comics with YACReader from YACReaderLibrary.
.TP
- Enjoy your comics covers with the fullscreen mode.
.TP
- Mark your comics as read/unread and track your reading progress.
.SH CONTACTS
To report bug or contact developpers, send a mail to :
.RS 3
.TP 
\fBinfo@yacreader.com\fR : for general information or suggestions about YACReader.
.TP
\fBsupport@yacreader.com\fR : for problems with YACReader or bugs detected.
.RE
.SH AUTHOR
Luis Ángel San Martín Rodríguez (luisangelsm@gmail.com)