.\" Manpage for YACReader.
.\" Contact yoann.gauthier9@gmail.com to correct errors or typos.
.TH man 8 "5 July 2014" "1.0" "YACReader man page"
.SH NAME
YACReader \- launch YACReader application.
.SH SYNOPSIS
.B
YACReader
pathfile
[\fIcomicId\fR]
[\fIlibraryId\fR]
.SH DESCRIPTION
YACReader is a free cross-platform comic reader with support for multiple comic files and image formats.
.SH OPTIONS
pathfile
: Path to be opened by YACReader.
.TP
\fIcomicId\fR : Comic identifier.
.TP
\fIlibraryId\fR : Library identifier. 
.SH FEATURES
- rar, zip, cbr, cbz, tar, pdf, 7z and cb7 comics support with compatibility for jpeg, gif, png, tiff and bmp images.
.TP
- Fast and easy to use.
.TP
- Use your keyboard or mouse for easy navigation.
.TP
- Fully customizable magnifying glass.
.TP
- Image rotation, double page mode, full size view, fullscreen mode, customizable background color and more.
.TP
- Bookmarks and resume reading.
.TP
- Find any page easily and quickly with "go to flow",  a customizable eye candy effect for browsing comic pages.
.SH CONTACTS
To report bug or contact developpers, send a mail to :
.RS 3
.TP 
\fBinfo@yacreader.com\fR : for general information or suggestions about YACReader.
.TP
\fBsupport@yacreader.com\fR : for problems with YACReader or bugs detected.
.RE
.SH AUTHOR
Luis Ángel San Martín Rodríguez (luisangelsm@gmail.com)