# YACReader tests

add_subdirectory(concurrent_queue_test)
add_subdirectory(compressed_archive_test)
add_subdirectory(continuous_view_model_test)
add_subdirectory(pdf_render_size_test)
add_subdirectory(folder_rename_test)
add_subdirectory(epub_page_index_test)
add_subdirectory(comic_files_manager_test)
add_subdirectory(organize_files_test)
add_subdirectory(yacreader_libraries_test)
