/*--------------------------------------------------------------------
*
* Due to issues with the dependencies checker within the IDE, it
* sometimes fails to recompile the PCH file, if we force the IDE to
* This file is auto-generated by qmake since no PRECOMPILED_SOURCE was
* specified, and is used as the common stdafx.cpp. The file is only
* command line compilations by nmake.
*
--------------------------------------------------------------------*/
#include "StdAfx.h"
